# Generated by Django 4.0.2 on 2022-02-28 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_customer_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='basket',
        ),
    ]
