# Generated by Django 4.0.2 on 2022-02-28 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_delete_basket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer',
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.product',),
        ),
    ]
