# Generated by Django 4.0.2 on 2022-02-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_delete_customer_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer',
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=32)),
            ],
        ),
    ]
