# Generated by Django 4.0.2 on 2022-02-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_delete_customer_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='basket',
            field=models.ManyToManyField(to='shop.product'),
        ),
    ]
