# Generated by Django 4.0.2 on 2022-03-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_customer_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buy',
            field=models.IntegerField(default=100),
        ),
    ]
